[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pr-lstm"
version = "1.0.0"
dependencies = [
  "dm-haiku",
  "jax[cuda12] ; sys_platform == 'linux'",
  "jax ; sys_platform != 'linux'",
  "dotenv",
  "wandb",
  "einops",
  "absl-py",
  "dm-tree",
  "einshape @ git+https://github.com/deepmind/einshape",
  "optax",
  "tqdm",
  "typing-extensions",
  "flax",
  "pluggy",
  "sympy",
  "chex",
]
authors = [
  { name = "Tristan Gaudreault", email = "tristan@tristangaudreault.com" },
]
description = "Implementation of the PR-LSTM architecture in dm-haiku."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/tristangaudreault/pr-lstm"
Issues = "https://github.com/tristangaudreault/pr-lstm/issues"

[tool.hatch.metadata]
allow-direct-references = true
