[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pr-lstm"
version = "1.0.0"
dependencies = [
  "dotenv",
  "wandb",
  "einops",
  "optax",
  "tqdm",
  "typing-extensions",
  "flax",
  "pluggy",
  "sympy",
  "chex",
]
authors = [
  { name = "Tristan Gaudreault", email = "tristan@tristangaudreault.com" },
]
description = "Implementation of the PR-LSTM architecture in dm-haiku."
readme = "README.md"
requires-python = "==3.11.15"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/tristangaudreault/pr-lstm"
Issues = "https://github.com/tristangaudreault/pr-lstm/issues"

[project.optional-dependencies]
torch = [
    "torch",
    "triton",
    "transformers[torch]",
    "datasets",
    "s5-pytorch",
]

jax = [
    "jax[cuda12] ; sys_platform == 'linux'",
    "jax ; sys_platform != 'linux'",
    "jaxlib",
    "dm-haiku",
    "dm-tree",
    "einshape @ git+https://github.com/deepmind/einshape",
]

dev = [
    "pytest",
    "tensorboard>=2.21.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
required-environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[[tool.uv.index]]
name = "pytorch-nightly-cu126"
url = "https://download.pytorch.org/whl/nightly/cu126"
explicit = false
