[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pr-lstm"
version = "1.0.0"
authors = [
  { name = "Tristan Gaudreault", email = "tristan@tristangaudreault.com" },
]
description = "PR-LSTM architecture implemented for PyTorch, Huggingface, and JAX."
readme = "README.md"
requires-python = ">=3.11,<3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/tristangaudreault/pr-lstm"
Issues = "https://github.com/tristangaudreault/pr-lstm/issues"

[project.optional-dependencies]
torch = ["torch", "s5-pytorch"]

hf = ["torch", "s5-pytorch", "transformers[torch]"]

jax = [
  "jax[cuda13] ; sys_platform == 'linux'",
  "jax ; sys_platform != 'linux'",
  "dm-haiku",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
required-environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[[tool.uv.index]]
name = "pytorch-nightly-cu126"
url = "https://download.pytorch.org/whl/nightly/cu126"
explicit = false
